apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  # 指定したラベルにマッチする Pod に Service へのアクセスが割り振られる
  type: NodePort
  selector:
    app: nginx
---

apiVersion: apps/v1
# 定義の種類
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  # 指定した条件に一致する Pod をこの Deployment が管理する (ここではlabelが一致すること)
  selector:
    matchLabels:
      app: nginx
  # レプリカ数: レプリカとは複数のことで、ここの数字分の Pod を常に起動させる
  replicas: 1
  # 作成する Pod の定義
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # Pod で起動するコンテナの定義 (Docker hubから取ってくる image を記載する)
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

