apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Secret を生成
secretGenerator:
  - name: app-secrets
    files:
      - username
      - password

generatorOptions:
  disableNameSuffixHash: true
